# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode7
language: objective-c
cache: cocoapods
podfile: Demo/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Demo
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Demo/Demo.xcworkspace -scheme EasyIOS-Swift -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
notifications:
  webhooks: https://hooks.pubu.im/services/21x4lqp4vepnfbn
